import pptxgen from 'pptxgenjs';
import { DocumentChunk, DocumentTheme } from '../store/useAppStore';

export const exportToPPTX = async (chunks: DocumentChunk[], theme: DocumentTheme) => {
  const pres = new pptxgen();

  // Set presentation properties
  pres.author = 'DocuGen Pro';
  pres.company = 'AI Generator';
  pres.revision = '1';
  pres.subject = 'Auto-Generated Presentation';

  // Add Master Slide for styling
  pres.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: theme.bgColor.replace('#', '') },
    objects: [
      {
        text: {
          text: 'Generated by DocuGen Pro',
          options: {
            x: 0.5,
            y: 5.2,
            w: 9.0,
            h: 0.2,
            fontSize: 10,
            color: theme.textColor.replace('#', ''),
            fontFace: theme.fontFamilyBody.split(',')[0].replace(/['"]/g, ''),
            align: 'right',
            margin: 0
          }
        }
      }
    ]
  });

  // Title Slide
  const titleSlide = pres.addSlide({ masterName: 'MASTER_SLIDE' });
  titleSlide.addText('Auto-Generated Document Outline', {
    x: 1.0,
    y: 2.0,
    w: 8.0,
    h: 1.0,
    fontSize: 44,
    bold: true,
    color: theme.textColor.replace('#', ''),
    fontFace: theme.fontFamilyHeading.split(',')[0].replace(/['"]/g, ''),
    align: 'center'
  });

  // Content Slides
  for (const chunk of chunks) {
    const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });
    
    // Add title
    slide.addText(chunk.sectionTitle, {
      x: 0.5,
      y: 0.5,
      w: 9.0,
      h: 0.8,
      fontSize: 32,
      bold: true,
      color: theme.textColor.replace('#', ''),
      fontFace: theme.fontFamilyHeading.split(',')[0].replace(/['"]/g, '')
    });

    // Parse content
    // Basic Markdown strip to plain text or basic bullet points
    const plainText = chunk.content
      .replace(/#+\s/g, '') // remove headers
      .replace(/\*\*/g, '') // remove bold
      .replace(/\n\n/g, '\n') // reduce double newlines
      .substring(0, 800) + (chunk.content.length > 800 ? '...' : ''); // truncate for slides

    const lines = plainText.split('\n').filter(l => l.trim().length > 0).slice(0, 6); // Max 6 bullets
    
    const bulletItems = lines.map(line => ({
      text: line.replace(/^-\s/, '').trim(),
      options: { bullet: true }
    }));

    if (bulletItems.length > 0) {
      slide.addText(bulletItems, {
        x: 0.5,
        y: 1.5,
        w: 9.0,
        h: 3.5,
        fontSize: 18,
        color: theme.textColor.replace('#', ''),
        fontFace: theme.fontFamilyBody.split(',')[0].replace(/['"]/g, ''),
        valign: 'top',
        margin: 0
      });
    }
  }

  // Save the presentation
  await pres.writeFile({ fileName: `DocuGen_Pro_${new Date().getTime()}.pptx` });
};
